id: CHG_STOCKS_CY
name:
  en: Changes in stocks
  fr: Variation des stocks
  nl: Voorraadverandering
unit: pp_contribution
frequency: A
source_id: nbb
geo_levels:
- national
preferred_direction: contextual
description:
  en: Changes in inventories, contribution to GDP volume change
fetch:
  query: ',DF_QNA_DISS,1.0/A.2.P52.VZ.CY.N?startPeriod=2006&dimensionAtObservation=AllDimensions'
display:
  category: gdp
  title:
    en: Changes in Inventories
    fr: Variation des stocks
    nl: Veranderingen in voorraden
  sort_order: 9
  sdmx_code: P52
