id: EC_CONS_CONF_EU
unit: balance
frequency: M
source_id: dbnomics_eurostat
geo_levels:
- national
fetch:
  query: /ei_bssi_m_r2/M.BS-CSMCI-BAL.SA.EU27_2020?observations=true
name:
  en: EC_CONS_CONF_EU
  fr: EC_CONS_CONF_EU
  nl: EC_CONS_CONF_EU
description:
  en: EU27 Consumer Confidence Indicator
display: null
