id: EUROSTAT_GDP_Q_MEUR_NL
name:
  en: GDP volume index, Netherlands (2010=100)
  fr: Indice de volume du PIB, Pays-Bas (2010=100)
  nl: Bbp-volume-index, Nederland (2010=100)
country: NL
unit: index_2010
frequency: Q
source_id: dbnomics_eurostat
geo_levels:
- national
preferred_direction: neutral
fetch:
  query: /namq_10_gdp/Q.CLV10_MEUR.SCA.B1GQ.NL?observations=true
display: null
