id: EUROSTAT_GDP_Q_MEUR_ES
name:
  en: GDP volume index, Spain (2010=100)
  fr: Indice de volume du PIB, Espagne (2010=100)
  nl: Bbp-volume-index, Spanje (2010=100)
country: ES
unit: index_2010
transform:
  method: rebase
  base: 2010
frequency: Q
source_id: eurostat
geo_levels:
- national
preferred_direction: neutral
fetch:
  dataset: namq_10_gdp
  filters:
    unit: CLV10_MEUR
    s_adj: SCA
    na_item: B1GQ
    geo: ES
  since: "2008"
display: null
