id: EUROSTAT_GDP_Q_MEUR_FR
name:
  en: GDP volume index, France (2010=100)
  fr: Indice de volume du PIB, France (2010=100)
  nl: Bbp-volume-index, Frankrijk (2010=100)
country: FR
unit: index_2010
transform:
  method: rebase
  base: 2010
frequency: Q
source_id: dbnomics_eurostat
geo_levels:
- national
preferred_direction: neutral
fetch:
  query: /namq_10_gdp/Q.CLV10_MEUR.SCA.B1GQ.FR?observations=true
display: null
