id: EUROSTAT_GDP_Q_MEUR
name:
  en: GDP volume index, Belgium (2010=100)
  fr: Indice de volume du PIB, Belgique (2010=100)
  nl: Bbp-volume-index, België (2010=100)
unit: index_2010
frequency: Q
source_id: dbnomics_eurostat
geo_levels:
- national
preferred_direction: higher_is_better
description:
  en: Gross domestic product, seasonally adjusted
fetch:
  query: /namq_10_gdp/Q.CLV10_MEUR.SCA.B1GQ.BE?observations=true
display: null
