id: LABOUR_COST_FR
name:
  en: LABOUR_COST_FR
  fr: LABOUR_COST_FR
  nl: LABOUR_COST_FR
country: FR
unit: index_2010
frequency: A
source_id: dbnomics_ameco
geo_levels:
- national
preferred_direction: neutral
description:
  en: Nominal compensation per employee, total economy (2010=100) - France
fetch:
  query: /PLCD/FRA.3.1.99.0.PLCD?observations=true
display: null
