id: LABOUR_COST_DE
name:
  en: Nominal compensation per employee, Germany (2010=100)
  fr: Rémunération nominale par salarié, Allemagne (2010=100)
  nl: Nominale beloning per werknemer, Duitsland (2010=100)
country: DE
unit: index_2010
frequency: A
source_id: dbnomics_ameco
geo_levels:
- national
preferred_direction: neutral
description:
  en: Nominal compensation per employee, total economy (2010=100) - Germany
fetch:
  query: /PLCD/DEU.3.1.99.0.PLCD?observations=true
display: null
