id: LABOUR_COST_DE
name:
  en: LABOUR_COST_DE
  fr: LABOUR_COST_DE
  nl: LABOUR_COST_DE
country: DE
unit: index_2010
frequency: A
source_id: dbnomics_ameco
geo_levels:
- national
preferred_direction: neutral
description:
  en: Nominal compensation per employee, total economy (2010=100) - Germany
fetch:
  query: /PLCD/DEU.3.1.99.0.PLCD?observations=true
display: null
