id: LABOUR_COST_EA
name:
  en: Nominal compensation per employee, euro area (2010=100)
  fr: Rémunération nominale par salarié, zone euro (2010=100)
  nl: Nominale beloning per werknemer, eurozone (2010=100)
country: EA
unit: index_2010
frequency: A
source_id: dbnomics_ameco
geo_levels:
- national
preferred_direction: neutral
description:
  en: Nominal compensation per employee, total economy (2010=100) - Euro Area
fetch:
  query: /PLCD/EA20.3.1.99.0.PLCD?observations=true
display: null
